version: '3'
services:
  replica-1:
    image: "${UTT_DEMO_REPLICA_IMAGE}:${UTT_DEMO_REPLICA_IMAGE_TAG}"
    command: -i 0
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
      - ${UTT_DEMO_VOLUME_ROCKSDB}
    expose:
      - ${UTT_DEMO_BFT_PORT}/udp
      - ${UTT_DEMO_BFT_PORT}/tcp
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_REPLICA_1_IP}

  replica-2:
    image: "${UTT_DEMO_REPLICA_IMAGE}:${UTT_DEMO_REPLICA_IMAGE_TAG}"
    command: -i 1
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
      - ${UTT_DEMO_VOLUME_ROCKSDB}
    expose:
      - ${UTT_DEMO_BFT_PORT}/udp
      - ${UTT_DEMO_BFT_PORT}/tcp
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_REPLICA_2_IP}

  replica-3:
    image: "${UTT_DEMO_REPLICA_IMAGE}:${UTT_DEMO_REPLICA_IMAGE_TAG}"
    command: -i 2
    expose:
      - ${UTT_DEMO_BFT_PORT}/udp
      - ${UTT_DEMO_BFT_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
      - ${UTT_DEMO_VOLUME_ROCKSDB}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_REPLICA_3_IP}

  replica-4:
    image: "${UTT_DEMO_REPLICA_IMAGE}:${UTT_DEMO_REPLICA_IMAGE_TAG}"
    command: -i 3
    expose:
      - ${UTT_DEMO_BFT_PORT}/udp
      - ${UTT_DEMO_BFT_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
      - ${UTT_DEMO_VOLUME_ROCKSDB}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_REPLICA_4_IP}

  payment-service-1:
    image: "${UTT_DEMO_PAYMENT_SERVICE_IMAGE}:${UTT_DEMO_PAYMENT_SERVICE_IMAGE_TAG}"
    command: -i 1
    expose:
      - ${UTT_DEMO_BFT_PORT}/udp
      - ${UTT_DEMO_BFT_PORT}/tcp
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_PAYMENT_SERVICE_1_IP}

  payment-service-2:
    image: "${UTT_DEMO_PAYMENT_SERVICE_IMAGE}:${UTT_DEMO_PAYMENT_SERVICE_IMAGE_TAG}"
    command: -i 2
    expose:
      - ${UTT_DEMO_BFT_PORT}/udp
      - ${UTT_DEMO_BFT_PORT}/tcp
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_PAYMENT_SERVICE_2_IP}

  payment-service-3:
    image: "${UTT_DEMO_PAYMENT_SERVICE_IMAGE}:${UTT_DEMO_PAYMENT_SERVICE_IMAGE_TAG}"
    command: -i 3
    expose:
      - ${UTT_DEMO_BFT_PORT}/udp
      - ${UTT_DEMO_BFT_PORT}/tcp
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_PAYMENT_SERVICE_3_IP}

  wallet-1:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 1
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_1_IP}

  wallet-2:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 2
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_2_IP}

  wallet-3:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 3
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_3_IP}

  wallet-4:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 4
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_4_IP}

  wallet-5:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 5
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_5_IP}

  wallet-6:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 6
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_6_IP}

  wallet-7:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 7
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_7_IP}

  wallet-8:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 8
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_8_IP}

  wallet-9:
    image: "${UTT_DEMO_WALLET_IMAGE}:${UTT_DEMO_WALLET_IMAGE_TAG}"
    command: -i 9
    expose:
      - ${UTT_DEMO_PUBLIC_API_PORT}/udp
      - ${UTT_DEMO_PUBLIC_API_PORT}/tcp
    volumes:
      - ${UTT_DEMO_VOLUME_LOG}
    networks:
      utt-demo-net:
        ipv4_address: ${UTT_DEMO_WALLET_9_IP}

networks:
  utt-demo-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${UTT_DEMO_SUBNET}
